name: Build example - nRF Connect SDK

on:
    push:
        branches:
            - master
            - 'v*-branch'
    pull_request:
    merge_group:
    workflow_dispatch:
        inputs:
            ncs_revision:
                description: "NCS branch or commit SHA"
                required: true
                default: "origin/master"

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
    cancel-in-progress: true

env:
    CHIP_NO_LOG_TIMESTAMPS: true

jobs:
    nrfconnect:
        name: nRF Connect SDK

        env:
            BUILD_TYPE: nrfconnect

        runs-on: ubuntu-latest
        if: github.actor != 'restyled-io[bot]'

        container:
            image: ghcr.io/project-chip/chip-build-nrf-platform:174
            volumes:
                - "/tmp/bloat_reports:/tmp/bloat_reports"
                - "/:/runner-root-volume"

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Free up disk space on the github runner
              uses: ./.github/actions/cleanup-runner
            - name: Checkout submodules & Bootstrap
              uses: ./.github/actions/checkout-submodules-and-bootstrap
              with:
                platform: nrfconnect
            - name: Cleanup unuseful directories
              run: |
                rm -rf ./.environment
            # Workaround, in docker image there is a change in the zephyr-env.sh script that breaks the checkout process.
            # We need to restore the zephyr-env.sh script to the original state.
            # It should be fixed during the next NCS bump in the Matter upstream repository.
            - name: Pre-update NCS
              run: |
                  cp $ZEPHYR_BASE/zephyr-env.sh $ZEPHYR_BASE/../zephyr-env.sh
                  git -C /opt/NordicSemiconductor/nrfconnect/zephyr stash
            - name: Update NCS recommended version (workflow_dispatch)
              if: github.event_name == 'workflow_dispatch'
              run: |
                  echo "Using NCS from ${{ github.event.inputs.ncs_revision }}"
                  echo "${{ github.event.inputs.ncs_revision }}" > config/nrfconnect/.nrfconnect-recommended-revision
            - name: Update NCS recommended version (pull_request)
              if: github.event_name == 'pull_request'
              env:
                  PR_DESCRIPTION: "${{ github.event.pull_request.body }}"
              run: |
                  if [ -n "$PR_DESCRIPTION" ]; then
                      NCS_PR_ID=$(echo $PR_DESCRIPTION | { grep 'NCS PR' || true; } | sed 's/.*nrfconnect\/sdk-nrf//' | { grep -oE '[0-9]+' || true; })
                      if [ -n "$NCS_PR_ID" ]; then
                          echo "Using NCS from pull/$NCS_PR_ID/head"
                          git -C $ZEPHYR_BASE/../nrf fetch origin pull/$NCS_PR_ID/head:NCS_PR
                          echo NCS_PR > config/nrfconnect/.nrfconnect-recommended-revision
                      else
                          echo "Using NCS from $(cat config/nrfconnect/.nrfconnect-recommended-revision)"
                      fi
                  fi
            - name: Check nRF Connect SDK revision.
              run: scripts/run_in_build_env.sh "python3 scripts/setup/nrfconnect/update_ncs.py --update --shallow"
              continue-on-error: true
            - name: Run unit tests of factory data generation script
              run: |
                  scripts/run_in_build_env.sh 'source $ZEPHYR_BASE/../zephyr-env.sh && pip3 install -r scripts/setup/requirements.nrfconnect.txt'
                  scripts/run_in_build_env.sh 'source $ZEPHYR_BASE/../zephyr-env.sh && ./scripts/tools/nrfconnect/tests/test_generate_factory_data.py'
                  rm -rf out/nrf-native-sim-tests
                  rm -rf src/test_driver/nrfconnect/build
            - name: Run unit tests for Zephyr native_posix_64 platform with NVS
              run: |
                  scripts/run_in_build_env.sh 'source $ZEPHYR_BASE/../zephyr-env.sh && ./scripts/build/build_examples.py --target nrf-native-sim-tests build'
                  rm -rf out/nrf-native-sim-tests
                  rm -rf src/test_driver/nrfconnect/build
            - name: Run unit tests for Zephyr native_posix_64 platform with ZMS
              run: |
                  scripts/run_in_build_env.sh "source $ZEPHYR_BASE/../zephyr-env.sh && scripts/examples/nrfconnect_example.sh ../src/test_driver native_sim -DCONFIG_ZMS=y -DCONFIG_ZMS_LOOKUP_CACHE=y -DCONFIG_ZMS_LOOKUP_CACHE_SIZE=512 -DCONFIG_ZMS_LOOKUP_CACHE_FOR_SETTINGS=y -DCONFIG_NVS=n"
                  ctest --build-nocmake -V --output-on-failure --test-dir src/test_driver/nrfconnect/build/nrfconnect --no-tests=error
                  rm -rf out/nrf-native-sim-tests
                  rm -rf src/test_driver/nrfconnect/build
            - name: Uploading Failed Test Logs
              uses: actions/upload-artifact@v4
              if: ${{ failure() && !env.ACT }}
              with:
                  name: test-log
                  path: |
                      src/test_driver/nrfconnect/build/Testing/Temporary/LastTest.log
